### ISSUE TITLE
Wonder Swan Color folder not appearing in Games

### ISSUE THREAD

**Issue by killerdude23233** [tenlevels/spruce#10]
I've added quite a few .wsc extension titles to the WSC folder under Roms, and everything else seems to be appearing correctly except WSC games. I can Load Content any WSC game in Retroarch manually and I have verified the files do open and run normally this way, but the OS doesn't generate the WSC folder in games. How do I fix this?

Edit: thank you to fengfrw for pointing me in the right direction. I had to add the wsc extension to lines in 2 different files: the first under *Emu/WSC/config_hidden.json and the second under *.tmp_update/hide_emulators.sh and it now shows up as expected.

**Comment by fengfrw** [comment]
Try adding wsc suffix in json of wsc, and then restart it.

**Comment by tenlevels** [comment]
I will add this to the next update. My files are zipped so it worked when I tested. Thanks for letting me know!
