### ISSUE TITLE
Cannot save states or properly exit game on 1.2.3

### ISSUE THREAD

**Issue by jamessteininger** [tenlevels/spruce#11]
Additionally I cannot get any GBA or SNES games to open. GB games and GBC are opening fine, but when I try to save a state it fails, and when I exit the system freezes completely. I can hold the power button to get the same to exit.

**Comment by jamessteininger** [comment]
It flashes "Create Cache" for a second then closes when I try to open most game platforms. I did replace my BIOS into the BIOS folder on the main directory.

**Comment by tenlevels** [comment]
This behavior I have never heard. I would recommend a fresh install. And may I ask what OS did you use to do the install? Windows PC or other?
