### ISSUE TITLE
Disable automatic CPU frequency setting

### ISSUE THREAD

**Issue by abhayap** [tenlevels/spruce#12]
Hi Tenlevels, how can disable the automatic CPU frequency setting for each core? If I'm playing games that are not too demanding I'd like to manually set a lower CPU frequency in the settings so I can get longer battery life and the device gets less hot. Does this make sense? 

Can I comment out this line in `launch.sh`?
```
$EMU_DIR/overclock 1344
```

Thanks!

**Comment by tenlevels** [comment]
Yes you can comment that out. We will try and figure out a solution to allow users to change cpu per core.
