### ISSUE TITLE
Pokemon Mini Control Mapping 

### ISSUE THREAD

**Issue by Kenny417** [tenlevels/spruce#13]
I performed a fresh install of Spruce today and tried to play Pokemon Pinball Mini but none of the buttons would work the plunger to launch the ball. I had to go into RetroArch settings and map the R Button to "C" and for good measure decided to map L Button to "Shake" (to mimic the control layout on my Steam Deck. 

Is it possible to update Spruce so this is mapped by default?

**Comment by tenlevels** [comment]
Thank you for the suggestion and heads up. I just pushed a new release with this. Cheers!
