### ISSUE TITLE
Problem with GPSP from main menu

### ISSUE THREAD

**Issue by ChrisXe** [tenlevels/spruce#14]
I'd like to use GPSP as my GBA core, but there seems to be a problem when launching from the home menu.
The image is flipped 90 degrees and also glitching with the spruce loading icon in the background.
The GPSP core is running fine if I load it from retroarch itself.

**Comment by tenlevels** [comment]
Please try a fresh install. And to make GPSP your default for now rename the launch1 to launch in the GBA Emu folder. We are working on a solution to allow users to change default core and cpu control soon.
