### ISSUE TITLE
Adding an app to sync saves in the background

### ISSUE THREAD

**Issue by josegonzalez** [tenlevels/spruce#15]
One thing I'm missing is the ability to sync saves to/from a remote server. It would be great to be able to set something up such that we could manually/automatically sync saves to a remote server (and get some sort of confirmation that this is happening).

Is there a guide somewhere to creating an app for SpruceOS? If there was, I could possibly contribute such a thing :)

Note: I know Syncthing exists, so if that works here, that would be fine too!

**Comment by tenlevels** [comment]
Syncthing we have working but Miyoo needs to resolve their Wi-Fi issues first before being added to spruce. Please find me on Discord and we can chat there about apps and other new fun stuff for spruce! tenlevels and I am on Retro Game Hanhelds and Retro Handhelds server. Cheers!
