### ISSUE TITLE
Image generation documentation

### ISSUE THREAD

**Issue by josegonzalez** [tenlevels/spruce#16]
Is there documentation somewhere on how to get images/description data into place for Spruce? Specifically image sizes, file placement, and any other extra metadata that we might be able to add would be awesome to know.

**Comment by tenlevels** [comment]
Right now the only images supported are box art and that info is in the zip. Perhaps we could use some help on documentation if you are interested in helping. Metadata/descriptions are currently not supported. But if you or someone knows a way that would be neat!
