### ISSUE TITLE
GBA Enhanced GBC games not loading in Gambatte, override not loading mGBA core

### ISSUE THREAD

**Issue by killerdude23233** [tenlevels/spruce#17]
In previous versions of Spruce I was able to open the game (such as LoZ: OoA) in the Retroarch app with the mGBA core, save the game override, then next time I launched it from the games list it would open with mGBA every time. Now it defaults to gambatte even after I save the override. (Edit: this is a problem because gambatte locks up after the start-up Game Boy Color splash screen and does not load into the game)

Any idea as to why and how to set cores for individual games such as GBA enhanced games, or other games that may run better on certain cores than others (such as many Pokemon rom hacks that run better in mGBA than gpSP)?

**Comment by tenlevels** [comment]
You can use Super Game Boy emulator folder for you enhanced games with MGBA. I am currently working on a solution for you to choose cores for systems. I do not know of a way to have a game from one system launch with a different core than the others in that system. Feel free to find me on Discord and we can chat further. I am closing this as it is not a spruce issue but perhaps limitations on the Miyoo or something that is a feature that could be added. Cheers!

**Comment by killerdude23233** [comment]
I was actually able to get it working with gambatte by playing around with the core options, so that may be a default config consideration for a future releases. I changed the following to get it to load, then a few more to get it to look prettier.

### To get it to boot with GBA enhanced features:
**Core Options:**
- Emulated Hardware (Restart Required): **GBA**
- Use Official Bootloader (Restart Required): **OFF** <-- This is why it would lock up after the start-up logo animation. I would guess it has to do with the start-up code the GBA enhanced games implemented to tell what kind of hardware it was playing on.
**Overrides:**
- Save Content Directory Overrides

### For prettier colors on par with the defaults in OnionOS:
**Core Options:**
- GB Colorization: GBC
- Current category color for palettes: Multicolor
- Color Categories -> Multicolor: Double Rainbow OMG
- Color Correction: OFF

Then of course video filters and borders can be set up to taste. I prefer integer scaling with Dot_Matrix_3x_Grid myself combined with the Darkhorse GBC_int_logo.cfg overlay.

Hope this info helps anyone else struggling with this issue. I don't foresee it causing problems with other GBC games, but I'll report back if I run into anything.
