### ISSUE TITLE
Spruce 1.3c not installing..

### ISSUE THREAD

**Issue by zhengzhongren** [tenlevels/spruce#19]
i have unzipped and copied the contents of the OS to a freshly formatted FAT32 Sandisk SD card. I turned on the device and after "Installing" shows for awhile, it disappears and the screen is empty and nothing happens.. Can someone please assist? thank you so much..

**Comment by tenlevels** [comment]
Please find us on Discord or Reddit. Users tenlevels and sundownersport. We would love to help!
