### ISSUE TITLE
Beetle Supafaust not working; how to change core association?

### ISSUE THREAD

**Issue by Fan-Fan** [tenlevels/spruce#2]
clean installed for v1.1, Beetle SUPAFAUST is not working but snes9x can. However, Supafaust is always chosen as default, causing inconvenience every time i want to start playing SNES games. How can i change default core association in SNES directory?

**Comment by tenlevels** [comment]
I just downloaded 1.1. Fresh format my card to Fat32 and extracted the zip. I then added one SNES game only. My install was clean and game launches. Please try this and report back. I am unable to duplicate this issue at this time.

**Comment by Fan-Fan** [comment]
So i formatted and fresh install again and now it works, i guess it was a faulty on SD Card when formatting or something. The question still stands though, in the future if i want to, can i change default core association in the game directory, (if can, how? is it a standard retroarch steps?)

Really great work on the firmware though, thumbs up!

**Comment by tenlevels** [comment]
Great news! You can go into the Emu folder and change launch1 to launch for now. launch.sh is the default and launch1.sh is the secondary core (if we have an option). Cheers!
