### ISSUE TITLE
black box fonts in ppsspp

### ISSUE THREAD

**Issue by elaxius** [tenlevels/spruce#20]
![20240710_165302](https://github.com/tenlevels/spruce/assets/94586786/04325f9c-9499-45a3-a4f0-b73a4f911a8f)

Encountered issue with fonts while playing FF3 on PSP. This seems to be a ppsspp core issue. Found this reddit thread on it
https://www.reddit.com/r/RetroArch/comments/18b6bxd/weird_black_boxes_for_font_in_system_menu_for/

**Comment by tenlevels** [comment]
This will need to be resolved by steward who did the PSP standalone. Hopeful he does the latest version as well soon.
