### ISSUE TITLE
No CHD support for PPSSPP

### ISSUE THREAD

**Issue by OneOfaKindDPC** [tenlevels/spruce#22]
Being on PPSSPP 1.16, there is no support for CHD like there is in 1.17.1. Is there any chance of moving to the newer version of PPSSPP?

Thank you in advance!

**Comment by tenlevels** [comment]
We would love for someone to figure that out and submit it. If you do we will give you credit. Cheers!

**Comment by OneOfaKindDPC** [comment]
Pretty sure someone already did as I had CHD support on the stock OS with this https://github.com/steward-fu/website/releases/tag/miyoo-a30

https://github.com/steward-fu/website/releases/download/miyoo-a30/rel_psp-v1.0.zip

**Comment by OneOfaKindDPC** [comment]
Steward already has a ppsspp 1.17.1 version on his github, and has for a while

https://github.com/steward-fu/website/releases/download/miyoo-a30/rel_psp-v1.0.zip
