### ISSUE TITLE
Mame 2003 Plus key bindings

### ISSUE THREAD

**Issue by laesetuc** [tenlevels/spruce#25]
Hi there, appreciate the work being done on Spruce!

I have an issue with key bindings using mame 2003 plus core. 
Basically I think the Y and A buttons are not mapped correctly.

When I press either of those two buttons, it is as if both those buttons are being pressed at the same time.

I have installed Spruce onto a fresh SD card, then added "Done Set 2" roms.
I've also gone and deleted all the .cfg files under /saves/Mame_2003-Plus/mame2003-plus/cfg  but that doesn't seem to fix the issue

I have a feeling I need to clear the button mappings in the mame menu.  If I bring up the mame menu via the L1 button, and go into Inputs, I can't figure out how to clear a button mapping.  If I press A for example it just waits for a button input and then assigns whatever button is pressed.

**Comment by laesetuc** [comment]
I should add that if I change the core to FB Alpha 2012 then all the buttons are mapped correctly.

**Comment by tenlevels** [comment]
Arcade is tricky sometimes. Which game are you playing so I can test, troubleshoot and see what is going on?

**Comment by laesetuc** [comment]
Thank you and I appreciate it. 
The game I am playing is Aliens vs Predator.

**Comment by laesetuc** [comment]
I think I found it - 
It's in Retroarch > Quick Menu > Core Options > Input > Input Interface > change from "simultaneous" to "retropad"

https://docs.libretro.com/library/mame2003_plus/

I think retropad should be the default, but not sure why it was set to simultaneous.
Same with the mame2003_extreme core as well.

**Comment by tenlevels** [comment]
I don't use Mame 2003+. Will make the change. I like FBNEO personally. Thanks for the heads up!
