### ISSUE TITLE
Pico-8 - Home button

### ISSUE THREAD

**Issue by laesetuc** [tenlevels/spruce#26]
Hi there, I'm using the native Pico-8 (dropped in the dyn and dat files in) and the games run fine.

When I press the Home button, it stops the game and goes to the command prompt.  if I press X then it switches back and forth between the Pico-8 editor and the command prompt.  But I can't get out of this screen - all the other buttons don't seem to be functional, apart from being able to move the cursor around and click on things in the editor.

How do we get out of this mode?

Is it possible to map the home button to the Pico-8 menu or just disable it to prevent the user getting stuck in this mode?

**Comment by tenlevels** [comment]
Press start in Pico-8 to bring up menu The home button does that weird behavior.
