### ISSUE TITLE
"BOOT LOGO APP" in 1.4.1 may brick the device.

### ISSUE THREAD

**Issue by game-de-it** [tenlevels/spruce#28]
Hello spruce developers.

As the title says, "BOOT LOGO APP" still has the potential to brick your A30.

- Background
A friend of mine reported that he bricked his A30 when he used "BOOT LOGO APP" on 1.4.1.
He used a pre-prepared image instead of one he created himself, but the process took more than 10 minutes to finish, so he rebooted the device and bricked it.

## Alternative

I came up with a system that displays the "bootlogo_splash.png" image in the spruce startup sequence.

- Change 1
I added the line "${SCRIPTS_DIR}/bootlogo_splash.sh" to line 25 of .tmp_update/runtime.sh.  
[runtime.sh.txt](https://github.com/user-attachments/files/16400640/runtime.sh.txt)

- Change 2
I added a new file ".tmp_update/scripts/bootlogo_splash.sh".  
[bootlogo_splash.sh.txt](https://github.com/user-attachments/files/16400641/bootlogo_splash.sh.txt)

With these changes, users only need to place a "bootlogo_splash.png" file with a resolution of "480x640" in the ".tmp_update/res" directory.
If the file does not exist, the series of processes will be ignored.

Note that internal processing stops while the "bootlogo_splash.png" file is displayed, so users who need to shorten the startup time can do so by changing the value of "SLEEP="2"" on the third line of the "bootlogo_splash.sh" file.

Check out the link below to see how it actually works.  
https://x.com/0_game_it/status/1817201606867497332

thank you.

**Comment by tenlevels** [comment]
If you used older spruce this was what we had. A logo that would show the same place you have here. I do not like adding another logo and more time to the boot up sequence. I have personally tested every single logo included and none brick my device.  If people do not want to use the boot logo app then they do not have to. But your friend may have a bad SD card or maybe an update will help. Again the images included do not cause a brick alone. It is something with your card or install.

**Comment by game-de-it** [comment]
Thank you for your reply.

If you don't want to slow down the boot time, you can always use the "BOOT LOGO APP" even if you know the risks. But I thought it would be better to give users the option to change the boot logo more safely, even if it slows down the boot time. That's why I posted this issue.

Of course, as stated in the notes, everything is done with the user's consent, so the OS is not responsible.

If, as you say, the problem is with the SD card, it seems like it can be avoided by checking that there is no problem with the file using the hash value.

You can close this issue.
Thank you for your time.
