### ISSUE TITLE
PSX List does not read miyoogamelist.xml

### ISSUE THREAD

**Issue by Underdogg0** [tenlevels/spruce#29]
PSX seems to ignore the miyoogamelist.xml file and display the full filenames instead.  I have heard this also happens for PSP/N64/DC, but I have not tested those myself.

**Comment by Underdogg0** [comment]
Retested on 1.4.2, this is fixed.

**Comment by tenlevels** [comment]
Correct... I resolved this in 1.4.2. Cheers!
