### ISSUE TITLE
Question: Loading slots buggable?

### ISSUE THREAD

**Issue by wuoarh** [tenlevels/spruce#30]
Hi there!

First of all, thank you so much for this awesome firmware! big enjoyer :)

Yesterday, I stumbled upon an issue with 1.4.2 and just confirmed 1.4.3 as well.

I had saves from before, 1.3.5 iirc. But none of those show the issues like for my DC Rayman 2 CHD.
On 1.3.5, they were fine, but some time (since upgrading?), Loading initially only showed 6/3 available. The more I saved, the more it became 6/10. But I'm never able to navigate away from Loading Slot 6. Saving seems to not be effected by this.

Also noteworthy that the first time it occured, I didn't even had a saved slot 6, only the first 1 or 2. I saved 6 manually then, and since then copy around.

I'm working around it by renaming my saves atm, the one I want to load currently needs to be .5.. Didn't find any other fix myself :/ Do you maybe spot the issue or maybe even bug?

Attaching screen of the saves, and similarly named saves next to it that don't have the issue, as well as still photos of the UI.

Thanks again and best

<img width="730" alt="Screenshot 2024-07-30 at 08 05 46" src="https://github.com/user-attachments/assets/97d31cfb-64d0-4393-8e46-f43ef1eed7a9">

![IMG_2529](https://github.com/user-attachments/assets/73dd1976-72a0-49b2-b0b7-b226170dc569)

![IMG_2530](https://github.com/user-attachments/assets/cd5e805e-c86c-486d-8c9a-e13bdb06d21b)

Edit: think I managed to produce sth similar without prior saves even. Example Super Diagonal Mario smw hack in SFC/kaizo sub folder. This one is more suspicious with the slash at least. Saved slot 1, none to load:

<img width="796" alt="Screenshot 2024-07-30 at 15 38 00" src="https://github.com/user-attachments/assets/8f32483c-fe39-4519-b03e-240128724c95">

![IMG_2536](https://github.com/user-attachments/assets/20e6194b-02a0-42c5-8f0a-667edece6107)

![IMG_2537](https://github.com/user-attachments/assets/d315d4c8-0fa8-4b38-ba3a-5120f442dca6)

**Comment by tenlevels** [comment]
I am unable to repeat an issue with save states. Mine work just fine. Have you tried a complete format of your card and reinstall? Is this for all saves and systems or only these two you mention?

**Comment by wuoarh** [comment]
Thanks for checking! So far can only hard confirm for these two - I'm not sure I've seen issues elsewhere.

A quick sd repair didn't change it, will try the full format and fresh install. Not sure I manage the (minimal) backup today, will report back asap, probably tomorrow or the day after.

**Comment by wuoarh** [comment]
Hey :) already got around to the backup done and trying.
Similar result, even with different SDs! Only copied over the 2 roms themselves, nothing else.


Rayman 2: Save Slot 1 -> Load Slot 6/1 appears, not loadable or navigatable
<img width="752" alt="Screenshot 2024-07-31 at 11 35 51" src="https://github.com/user-attachments/assets/51fa964b-d82a-4943-a995-f37823b50a17">
![IMG_2549](https://github.com/user-attachments/assets/4a3eb83e-9705-4f5d-8470-17e656f630e3)


Diagonal Mario: Save slot 1 -> no loading slot appears. Launching the game a second time loads the last state though. Also tried renaming the rom, changing the weird char to a space.
<img width="747" alt="Screenshot 2024-07-31 at 11 36 29" src="https://github.com/user-attachments/assets/ae6178ce-cfa0-4795-a9ed-b36802e1cef1">
![IMG_2550](https://github.com/user-attachments/assets/7e4c6fab-534d-4a8f-9dc5-588c32da1fab)


So I'm pretty confident the SD is not the culprit - maybe the roms themselves are somehow?
If you'd maybe like to reproduce, I uploaded them to my google drive: https://drive.google.com/drive/folders/13Kx8wFumyPhMZh6Dcv2o0wYcSODFr02L?usp=sharing


Just a thought: the save slots list the existing saves pretty unbuggy in these cases - if the load slots would do "the same", it'd be solved :)


Best and thanks again

**Comment by FC-jan** [comment]
thank you still for your time and effort :)
if I find any workarounds/solutions, I'd post them back here.

all the best

**Comment by wuoarh** [comment]
thank you still for your time and effort :)
if I find any workarounds/solutions, I'd post them back here.

all the best
