### ISSUE TITLE
Protect Retroarch custom configs when updating Spruce

### ISSUE THREAD

**Issue by sibob** [tenlevels/spruce#33]
I’ve made a lot of changes to Retroarch’s inputs and general config e.g. core options and vertical controls for TATE mode on FBNeo games.

Whenever a new Spruce version comes out (and following the instructions to update) it resets all this. I understand its because it's replacing the config files. I’ve started backing up my custom configs and reinstalling them folder-by-folder each time - but is there a way you could make updates protect these settings?

Thankyou

**Comment by tenlevels** [comment]
You can keep your RetroArch config folder.
