### ISSUE TITLE
Support java games

### ISSUE THREAD

**Issue by MaiklGureev** [tenlevels/spruce#35]
Hello, gentlemen. Do you have plans to add support for playing Java applications to the firmware?
I would really like to play old java games. I hope other comrades will support me.
https://github.com/aweigit/freej2me-miyoomini

There is already an implementation on the Miyoo Mini / Miyoo Mini Plus device.
for example
https://www.youtube.com/watch?v=Rggw1Q5AghA

**Comment by tenlevels** [comment]
If you or someone would like to contribute a working version for A30 yes it will be added. I am closing this issue for now.
