### ISSUE TITLE
Inaccurate README.txt / DS and PSP saves lost during OS update

### ISSUE THREAD

**Issue by Jamish** [tenlevels/spruce#38]
The update instructions in the README.txt are as follows:

> To update:
> Download the latest release and extract the contents
> Remove everything on your SD card except for BIOS and Roms and Saves folders
> Place the contents of the zip onto your SD card.
> This will retain all your games, saves, and emulator bios files.

However, this is not entirely accurate, because some emulators save in other directories, namely:
- DS saves are stored in `Emu/NDS/backup`
- PSP saves are stored in `.config/ppsspp/PSP/SAVEDATA`

Following the README.txt instructions results in loss of PSP and DS save games.

Thanks for all your hard work thus far. I've been enjoying the A30 thanks to this firmware!

**Comment by tenlevels** [comment]
This will be addressed. Thanks.
