### ISSUE TITLE
SNES games still not opening with Spruce 1.1.4

### ISSUE THREAD

**Issue by themsubtle** [tenlevels/spruce#4]
I actually tried 1.1.3 before I installed the latest release (1.1.4) seeing that there was a fix and unfortunately I still can't get them to run, it opens the spruce splash screen then goes back to the ROM list

Just thought I would let you guys know that still problem on some devices

**Comment by tenlevels** [comment]
I was told that a system reboot solves it. Does that do it for you? Thinking maybe this is a Miyoo bug? Not really sure.

**Comment by andrenoboru** [comment]
I'm on 1.1.3 and SNES is opening without issues

**Comment by tenlevels** [comment]
thanks andrenoboru - keep me posted if it happens.

**Comment by Fan-Fan** [comment]
This was exactly the same problem as me in this issue : [https://github.com/tenlevels/spruce/issues/2](https://github.com/tenlevels/spruce/issues/2)
(SUPAFAUST, the default core for SNES, was not working and crashed, was able to run SNES games by pushing X and choosing SNES9X). re-installed and te problem was gone. In above thread i thought it was a faulty in my formatting or something, but if it's reproducable by other people then maybe something is up?

**Comment by tenlevels** [comment]
Yeah Fan-Fan. I was able to repeat it. But then went away. It is so strange. Maybe a Miyoo bug? I could test Snes9x 2005 Plus as our default core and see if it happens. The other SNES9X on there now is a bit heavy. I feel like I am chasing my tail here a bit.

**Comment by themsubtle** [comment]
> I was told that a system reboot solves it. Does that do it for you? Thinking maybe this is a Miyoo bug? Not really sure.

Yes I have tried again this morning and after rebooting it does seem to work, but I would say it does seem a little slower than it was before, for example I tried Yoshi's island and seems slower than before (0.9 something I was on before)

**Comment by tenlevels** [comment]
I just changed the core to SNES9X2005 and uploaded new release. I have been trying to get SNES to lock up again and have not been able to yet.

**Comment by themsubtle** [comment]
> I just changed the core to SNES9X2005 and uploaded new release. I have been trying to get SNES to lock up again and have not been able to yet.

Awesome will get the new release downloaded, installed and give it a test, thanks again for your hard work on this project!!

**Comment by tenlevels** [comment]
Following up here... so SNES2005 does work. I noticed audio might not being great/accurate though now. I was simply testing for load and the bug/lock up. I think it might be best to use SNES9X instead. Again this is such a strange thing and I have only experienced this issue with the one SNES core not loading games.... so far anyway.

**Comment by themsubtle** [comment]
> Following up here... so SNES2005 does work. I noticed audio might not being great/accurate though now. I was simply testing for load and the bug/lock up. I think it might be best to use SNES9X instead. Again this is such a strange thing and I have only experienced this issue with the one SNES core not loading games.... so far anyway.

yeh i do think SNES9X work better and maybe slightly faster, and to be honest i haven't had the issue since after i installed so it could be something that happens after install and then rebooting fixes it, does seem like strange issue, hopefully we can go back to SNES9X as the main emulator eventually

**Comment by tenlevels** [comment]
I have done a bunch of reinstalls and combo of builds and I can get Mednafen Supafaust to just lock up and not load games. I will do more testing and of course encourage others to help. But it might have something to do with auto load and save state on that core. Yes I am planning to switch to SNES9X as the main core vs SNES9X2005. I am gonna wait a bit for some more feedback/input though. I am also considering to go back to MGBA for main and gpsp as option for GBA games. Better rom hack and rumble support is fun. :) Thanks again!

**Comment by themsubtle** [comment]
> I have done a bunch of reinstalls and combo of builds and I can get Mednafen Supafaust to just lock up and not load games. I will do more testing and of course encourage others to help. But it might have something to do with auto load and save state on that core. Yes I am planning to switch to SNES9X as the main core vs SNES9X2005. I am gonna wait a bit for some more feedback/input though. I am also considering to go back to MGBA for main and gpsp as option for GBA games. Better rom hack and rumble support is fun. :) Thanks again!

ah I forgot that mednafen supafast is the default SNES core usually, thats the one I use on my MMv2, and I believe thats the one that locked up for me too. awesome! of course happy to help where I can! yeh maybe it is something that will require a Miyoo update for that core to work properly, it's a shame as i've had good performance with that core before, will keep testing it though and see how I go with this release. Hopefully other will provide some feedback for you too!

I've always had much better performance with mGBA over gpsp, I know people prefer the fast forward or somthing on gpsp but I agree it seems better especially for hacks!

**Comment by tenlevels** [comment]
After so much testing the solution for now on the Mednafen Supafaust core is to disable auto save and load state for that core. For this reason we have chosen to have SNES9X as the main core to launch games with auto save and load and then Mednafen Supafaust as the other option for games that can benefit from that core such as Yoshi's Island. If anyone can find a solution that would be great. I am closing this issue for now. Thanks!

**Comment by themsubtle** [comment]
> After so much testing the solution for now on the Mednafen Supafaust core is to disable auto save and load state for that core. For this reason we have chosen to have SNES9X as the main core to launch games with auto save and load and then Mednafen Supafaust as the other option for games that can benefit from that core such as Yoshi's Island. If anyone can find a solution that would be great. I am closing this issue for now. Thanks!

Awesome nice one! That's good you've managed to narrow down the possible problem with the auto saves, it's good to still have it as an option for certain games IE Yoshi's island etc, hopefully this sorts the problem for a while until an official update or any other solutions found.
Thanks again for all your help!!
