### ISSUE TITLE
File Management and Pico-8 apps do not load

### ISSUE THREAD

**Issue by pgerken** [tenlevels/spruce#5]
On spruce.v1.1.2 and spruce.v1.1.3, when I try and load File Management and PICO-8, both appear to crash and goes back to the Apps list.  File Management on spruce.v1.09.1 worked fine.  I tried different SD cards, but still have the problem.

**Comment by pgerken** [comment]
I previously copied the spruce files from a Mac laptop to the sd card and that might have caused the problem.  I tried copying the files again using a Linux laptop and can now run the File Management app.  I'm copying over the PICO-8 Roms now and will see if they work when it's done.

**Comment by tenlevels** [comment]
Thanks for the update. The apps work for me. Don't forget you need the dat and dyn files for Pico-8.

**Comment by pgerken** [comment]
So I previous had pico-8 running games in spruce.v1.09.1 and the p8.png files were renamed to p8 and copied to a PICO folder. 

In spruce.v1.1.3, I copied them to the PICO8 dir and the games are listed but don't run.  I also tried to move them to the FAKE08 dir, but then the games were not listed.

What are the dat and dyn files for Pico-8?  I'm new to Pico-8 and it looks interesting, but I'm not sure I understand how it all works yet.

Thanks for the help!

**Comment by tenlevels** [comment]
FAKE08 is the old way and the .p8 files are needed. You will need to drag over FAKE08 from the .ADD ONS folder if you want to use that emulator. If Pico-8 native is available that will be my default as I am a big supporter of Pico-8 and what it allows for indie game makers. You will need to buy the Raspberry Pi version and place the dat and dyn files in the app bin folder. https://www.lexaloffle.com/games.php?page=updates You can download games for free from Pico-8 site. If you look on the SD card there are some .txt files with instructions and look in the .spruce folder as well. Happy gaming!

**Comment by pgerken** [comment]
That was it... I didn't drag over the FAKE08 folder.  The Pico8 games are now playable again.  I'm assuming once I have the dat and dyn files for Pico-8, then the Splore App will work.  Thanks again for the help!

**Comment by tenlevels** [comment]
Yes the app has a bin folder. PLace the dat and dyn files there. Splore will work and you can then launch pico-8 games through the games section using native. If real Pico-8 is an option it is the best/only way to play those games IMO. Fake has issues with audio and does not support bigger games like Kalikran. And yeah... I like supporting the new indie game makers. :) Cheers!
