### ISSUE TITLE
Update guide

### ISSUE THREAD

**Issue by josegonzalez** [tenlevels/spruce#6]
Given that there is only a single SD card slot on the device, we can't place roms on other carts and do an SD card update on the regular cart. Is there a prescribed method of upgrading Spruce?

**Comment by tenlevels** [comment]
Hello, you can delete everything except for your roms and bios folder on your sd card and drag contents of zip on.

**Comment by josegonzalez** [comment]
What about saves/save states? Are those stored in the roms/bios folder, or elsewhere?

**Comment by tenlevels** [comment]
Thanks. You are welcome to keep contributing as much as you would like. Yes the saves are located in the ROMS folder.

**Comment by tenlevels** [comment]
Feel free to find me on Discord or Reddit and we can chat more. I will close this issue for now.
