### ISSUE TITLE
Peformance significantly up (PSX, N64, PSP)

### ISSUE THREAD

**Issue by MasterEmerald** [tenlevels/spruce#9]
With the latest v1.2.1, performance and/or changes to the default cores or core settings for the three systems in the title has significantly improved vs 1.1.x builds. So much so that most worthwhile titles are now playable. Great job!

Sifting through retroarch settings (general and per core across many emulators), I did notice that logging is enabled by default, with fairly verbose granularity.  Consider turning that off across tbe board to improve performance. 

Also, sound output is defaulted to 48kHz sampling rate, maybe 44.1KHz would put let strain on the processors and fix some crackles and sound issues?

**Comment by abhayap** [comment]
How can I turn off logging in the retroarch configuration?

**Comment by MasterEmerald** [comment]
You can see it in the retroarch setup screen, one of the last sections is called logging and it defines the verbosity, etc.

There is a global default and per core defaults which I believe inherit from global in Spruce.

**Comment by tenlevels** [comment]
I will turn it off

**Comment by tenlevels** [comment]
I tried turning it off and it reverts back on.

**Comment by MasterEmerald** [comment]
Interesting, even after you save the default config (retroarch config default)? 
I believe I have been able go disable it and have that presist with v1.2.1
